# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "ability_mods", :force => true do |t|
    t.column "mod",     :integer, :null => false
    t.column "bonus_1", :integer, :null => false
    t.column "bonus_2", :integer, :null => false
    t.column "bonus_3", :integer, :null => false
    t.column "bonus_4", :integer, :null => false
    t.column "bonus_5", :integer, :null => false
    t.column "bonus_6", :integer, :null => false
    t.column "bonus_7", :integer, :null => false
    t.column "bonus_8", :integer, :null => false
    t.column "bonus_9", :integer, :null => false
  end

  add_index "ability_mods", ["mod"], :name => "mod"

  create_table "alignments", :force => true do |t|
    t.column "name",        :string, :default => "", :null => false
    t.column "description", :text
  end

  add_index "alignments", ["name"], :name => "name_index"

  create_table "character_items", :force => true do |t|
    t.column "character_id", :integer,                    :null => false
    t.column "item_id",      :integer,                    :null => false
    t.column "equipped",     :boolean, :default => false, :null => false
  end

  add_index "character_items", ["character_id"], :name => "character_id"
  add_index "character_items", ["item_id"], :name => "item_id"

  create_table "character_monsters", :force => true do |t|
    t.column "character_id", :integer, :null => false
    t.column "monster_id",   :integer, :null => false
    t.column "hp",           :integer
  end

  add_index "character_monsters", ["character_id"], :name => "character_id"
  add_index "character_monsters", ["monster_id"], :name => "monster_id"

  create_table "character_spells", :force => true do |t|
    t.column "character_id", :integer, :null => false
    t.column "spell_id",     :integer, :null => false
  end

  create_table "characters", :force => true do |t|
    t.column "player_name",    :string,  :default => "NPC",     :null => false
    t.column "character_name", :string,  :default => "unnamed", :null => false
    t.column "race",           :string,  :default => "Human",   :null => false
    t.column "class_type",     :string,  :default => "Fighter", :null => false
    t.column "weight",         :string,  :default => "100 lbs", :null => false
    t.column "height",         :string,  :default => "5\"",     :null => false
    t.column "hp",             :integer, :default => 1,         :null => false
    t.column "hp_max",         :integer, :default => 1,         :null => false
    t.column "ac_armor",       :integer, :default => 0,         :null => false
    t.column "ac_shield",      :integer, :default => 0,         :null => false
    t.column "size_mod",       :integer, :default => 2,         :null => false
    t.column "xp",             :integer, :default => 0,         :null => false
    t.column "strength",       :integer, :default => 10,        :null => false
    t.column "dexterity",      :integer, :default => 10,        :null => false
    t.column "constitution",   :integer, :default => 10,        :null => false
    t.column "intelligence",   :integer, :default => 10,        :null => false
    t.column "wisdom",         :integer, :default => 10,        :null => false
    t.column "charisma",       :integer, :default => 10,        :null => false
    t.column "speed",          :integer, :default => 25,        :null => false
    t.column "money_cp",       :integer, :default => 0,         :null => false
    t.column "money_sp",       :integer, :default => 0,         :null => false
    t.column "money_gp",       :integer, :default => 0,         :null => false
    t.column "money_pp",       :integer, :default => 0,         :null => false
    t.column "money_gems",     :text
    t.column "notes",          :text
    t.column "initiative_mod", :integer, :default => 0,         :null => false
    t.column "fortitude_mod",  :integer, :default => 0,         :null => false
    t.column "reflex_mod",     :integer, :default => 0,         :null => false
    t.column "will_mod",       :integer, :default => 0,         :null => false
    t.column "attack",         :string,  :default => "0",       :null => false
  end

  create_table "class_tables", :force => true do |t|
    t.column "name",                  :string, :limit => 100, :default => "", :null => false
    t.column "level",                 :string,                :default => ""
    t.column "base_attack_bonus",     :string,                :default => ""
    t.column "fort_save",             :string,                :default => ""
    t.column "ref_save",              :string,                :default => ""
    t.column "will_save",             :string,                :default => ""
    t.column "caster_level",          :string,                :default => ""
    t.column "points_per_day",        :string,                :default => ""
    t.column "ac_bonus",              :string,                :default => ""
    t.column "flurry_of_blows",       :string,                :default => ""
    t.column "bonus_spells",          :string,                :default => ""
    t.column "powers_known",          :string,                :default => ""
    t.column "unarmored_speed_bonus", :string,                :default => ""
    t.column "unarmed_damage",        :string,                :default => ""
    t.column "power_level",           :string,                :default => ""
    t.column "special",               :string,                :default => ""
    t.column "slots_0",               :string,                :default => ""
    t.column "slots_1",               :string,                :default => ""
    t.column "slots_2",               :string,                :default => ""
    t.column "slots_3",               :string,                :default => ""
    t.column "slots_4",               :string,                :default => ""
    t.column "slots_5",               :string,                :default => ""
    t.column "slots_6",               :string,                :default => ""
    t.column "slots_7",               :string,                :default => ""
    t.column "slots_8",               :string,                :default => ""
    t.column "slots_9",               :string,                :default => ""
    t.column "spells_known_0",        :string,                :default => ""
    t.column "spells_known_1",        :string,                :default => ""
    t.column "spells_known_2",        :string,                :default => ""
    t.column "spells_known_3",        :string,                :default => ""
    t.column "spells_known_4",        :string,                :default => ""
    t.column "spells_known_5",        :string,                :default => ""
    t.column "spells_known_6",        :string,                :default => ""
    t.column "spells_known_7",        :string,                :default => ""
    t.column "spells_known_8",        :string,                :default => ""
    t.column "spells_known_9",        :string,                :default => ""
    t.column "reference",             :string,                :default => ""
  end

  add_index "class_tables", ["id"], :name => "id"
  add_index "class_tables", ["name"], :name => "name"
  add_index "class_tables", ["level"], :name => "level"

  create_table "class_types", :force => true do |t|
    t.column "class_name",             :string, :limit => 100, :default => "", :null => false
    t.column "class_type",             :string
    t.column "alignment",              :string,                :default => ""
    t.column "hit_die",                :string,                :default => ""
    t.column "class_skills",           :text
    t.column "skill_points",           :string,                :default => ""
    t.column "skill_points_ability",   :string,                :default => ""
    t.column "spell_stat",             :string,                :default => ""
    t.column "proficiencies",          :text
    t.column "spell_type",             :string,                :default => ""
    t.column "epic_feat_base_level",   :string,                :default => ""
    t.column "epic_feat_interval",     :string,                :default => ""
    t.column "epic_feat_list",         :text
    t.column "epic_full_text",         :text
    t.column "req_race",               :string,                :default => ""
    t.column "req_weapon_proficiency", :string,                :default => ""
    t.column "req_base_attack_bonus",  :string,                :default => ""
    t.column "req_skill",              :string,                :default => ""
    t.column "req_feat",               :string,                :default => ""
    t.column "req_spells",             :string,                :default => ""
    t.column "req_languages",          :string,                :default => ""
    t.column "req_psionics",           :string,                :default => ""
    t.column "req_epic_feat",          :string,                :default => ""
    t.column "req_special",            :string,                :default => ""
    t.column "spell_list_1",           :text
    t.column "spell_list_2",           :string,                :default => ""
    t.column "spell_list_3",           :string,                :default => ""
    t.column "spell_list_4",           :string,                :default => ""
    t.column "spell_list_5",           :string,                :default => ""
    t.column "full_text",              :text
    t.column "reference",              :string,                :default => ""
  end

  add_index "class_types", ["id"], :name => "id"
  add_index "class_types", ["class_name"], :name => "name"

  create_table "equipment", :force => true do |t|
    t.column "name",                        :string, :limit => 100, :default => "", :null => false
    t.column "family",                      :string,                :default => ""
    t.column "category",                    :string,                :default => ""
    t.column "subcategory",                 :string,                :default => ""
    t.column "cost",                        :string,                :default => ""
    t.column "dmg_s",                       :string,                :default => ""
    t.column "armor_shield_bonus",          :string,                :default => ""
    t.column "maximum_dex_bonus",           :string,                :default => ""
    t.column "dmg_m",                       :string,                :default => ""
    t.column "weight",                      :string,                :default => ""
    t.column "critical",                    :string,                :default => ""
    t.column "armor_check_penalty",         :string,                :default => ""
    t.column "arcane_spell_failure_chance", :string,                :default => ""
    t.column "range_increment",             :string,                :default => ""
    t.column "speed_30",                    :string,                :default => ""
    t.column "type",                        :string,                :default => ""
    t.column "speed_20",                    :string,                :default => ""
    t.column "full_text",                   :text
    t.column "reference",                   :string,                :default => ""
  end

  add_index "equipment", ["id"], :name => "id"
  add_index "equipment", ["name"], :name => "name"
  add_index "equipment", ["category"], :name => "category"

  create_table "items", :force => true do |t|
    t.column "name",            :string,  :limit => 100
    t.column "category",        :string,                 :default => ""
    t.column "subcategory",     :string,                 :default => ""
    t.column "special_ability", :string,                 :default => ""
    t.column "caster_level",    :string,                 :default => ""
    t.column "price",           :string,                 :default => ""
    t.column "prereq",          :text
    t.column "weight",          :string,                 :default => ""
    t.column "full_text",       :text
    t.column "reference",       :string,                 :default => ""
    t.column "armor_bonus",     :integer
    t.column "damage",          :string,  :limit => 20
    t.column "critical",        :string,  :limit => 20
    t.column "range",           :string,  :limit => 20
  end

  add_index "items", ["id"], :name => "id"
  add_index "items", ["name"], :name => "name"
  add_index "items", ["category"], :name => "category"

  create_table "levels", :force => true do |t|
    t.column "xp",        :integer, :null => false
    t.column "skill_max", :integer, :null => false
    t.column "feats",     :integer, :null => false
  end

  add_index "levels", ["xp"], :name => "xp"

  create_table "monsters", :force => true do |t|
    t.column "family",            :string,                :default => ""
    t.column "name",              :string, :limit => 100, :default => "", :null => false
    t.column "altname",           :string,                :default => ""
    t.column "size",              :string,                :default => ""
    t.column "monster_type",      :string
    t.column "descriptor",        :string,                :default => ""
    t.column "hit_dice",          :string,                :default => ""
    t.column "initiative",        :string,                :default => ""
    t.column "speed",             :string,                :default => ""
    t.column "armor_class",       :string,                :default => ""
    t.column "base_attack",       :string,                :default => ""
    t.column "grapple",           :string,                :default => ""
    t.column "attack",            :string,                :default => ""
    t.column "full_attack",       :text
    t.column "space",             :string,                :default => ""
    t.column "reach",             :string,                :default => ""
    t.column "special_attacks",   :string,                :default => ""
    t.column "special_qualities", :text
    t.column "saves",             :string,                :default => ""
    t.column "abilities",         :string,                :default => ""
    t.column "skills",            :text
    t.column "bonus_feats",       :string,                :default => ""
    t.column "feats",             :text
    t.column "epic_feats",        :text
    t.column "environment",       :string,                :default => ""
    t.column "organization",      :text
    t.column "challenge_rating",  :string,                :default => ""
    t.column "treasure",          :string,                :default => ""
    t.column "alignment",         :string,                :default => ""
    t.column "advancement",       :string,                :default => ""
    t.column "level_adjustment",  :string,                :default => ""
    t.column "special_abilities", :text
    t.column "stat_block",        :text
    t.column "full_text",         :text
    t.column "reference",         :string,                :default => ""
  end

  add_index "monsters", ["id"], :name => "id"
  add_index "monsters", ["name"], :name => "name"
  add_index "monsters", ["monster_type"], :name => "monster_type"

  create_table "races", :force => true do |t|
    t.column "name",        :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

  create_table "skill", :force => true do |t|
    t.column "name",        :string, :limit => 100, :default => "", :null => false
    t.column "subtype",     :text
    t.column "key_ability", :string,                :default => ""
    t.column "psionic",     :string,                :default => ""
    t.column "trained",     :string,                :default => ""
    t.column "armor_check", :string,                :default => ""
    t.column "description", :text
    t.column "skill_check", :text
    t.column "action",      :text
    t.column "try_again",   :text
    t.column "special",     :text
    t.column "restriction", :text
    t.column "synergy",     :text
    t.column "epic_use",    :text
    t.column "untrained",   :text
    t.column "full_text",   :text
    t.column "reference",   :string,                :default => ""
  end

  add_index "skill", ["id"], :name => "id"
  add_index "skill", ["name"], :name => "name"

  create_table "spell", :force => true do |t|
    t.column "name",                       :string, :limit => 100, :default => "", :null => false
    t.column "altname",                    :string,                :default => ""
    t.column "school",                     :string,                :default => ""
    t.column "subschool",                  :string,                :default => ""
    t.column "descriptor",                 :string,                :default => ""
    t.column "spellcraft_dc",              :string,                :default => ""
    t.column "level",                      :string,                :default => ""
    t.column "components",                 :text
    t.column "casting_time",               :string,                :default => ""
    t.column "range",                      :string,                :default => ""
    t.column "target",                     :string,                :default => ""
    t.column "area",                       :string,                :default => ""
    t.column "effect",                     :string,                :default => ""
    t.column "duration",                   :string,                :default => ""
    t.column "saving_throw",               :string,                :default => ""
    t.column "spell_resistance",           :string,                :default => ""
    t.column "short_description",          :string,                :default => ""
    t.column "to_develop",                 :text
    t.column "material_components",        :text
    t.column "arcane_material_components", :string,                :default => ""
    t.column "focus",                      :text
    t.column "description",                :text
    t.column "xp_cost",                    :text
    t.column "arcane_focus",               :string,                :default => ""
    t.column "wizard_focus",               :string,                :default => ""
    t.column "verbal_components",          :string,                :default => ""
    t.column "sorcerer_focus",             :string,                :default => ""
    t.column "bard_focus",                 :string,                :default => ""
    t.column "cleric_focus",               :string,                :default => ""
    t.column "druid_focus",                :string,                :default => ""
    t.column "full_text",                  :text
    t.column "reference",                  :string,                :default => ""
  end

  add_index "spell", ["id"], :name => "id"
  add_index "spell", ["name"], :name => "name"

end
